# Generated by Django 3.0.3 on 2020-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dtB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtB_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtB_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtB_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtB_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtB_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtB_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dtB_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtBD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtBD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtBD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtBD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtBD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtBD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dtP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtP_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtP_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtP_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtP_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtP_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtP_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dtP_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtPD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtPD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtPD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtPD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtPD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dtPD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='lrB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrB_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrB_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrB_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrB_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrB_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrB_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='lrB_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrBD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrBD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrBD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrBD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrBD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrBD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='lrP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrP_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrP_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrP_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrP_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrP_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrP_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='lrP_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrPD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrPD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrPD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrPD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrPD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lrPD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='nbB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbB_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbB_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbB_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbB_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbB_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbB_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='nbB_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbBD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbBD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbBD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbBD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbBD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbBD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='nbP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbP_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbP_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbP_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbP_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbP_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbP_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='nbP_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbPD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbPD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbPD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbPD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbPD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nbPD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('blood_grp', models.CharField(max_length=4)),
                ('parents_name', models.CharField(blank=True, max_length=30, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=30, null=True)),
                ('result', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='rfB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfB_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfB_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfB_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfB_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfB_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfB_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rfB_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfBD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfBD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfBD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfBD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfBD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfBD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rfP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfP_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfP_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfP_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfP_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfP_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfP_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rfP_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfPD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfPD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfPD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfPD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfPD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rfPD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='svmB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svmB_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmB_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmB_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmB_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmB_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmB_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='svmB_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svmBD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmBD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmBD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmBD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmBD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmBD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='svmP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svmP_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmP_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmP_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmP_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmP_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmP_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='svmP_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svmPD_fold_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmPD_fold_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmPD_fold_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmPD_fold_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmPD_fold_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svmPD_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
